(function(){
  const {data,escapeHtml,money,qs,qsa,toast,api}=window.Fixindo;
  let professionals=[];
  const initials=(value='P')=>value.split(' ').map(part=>part[0]).join('').slice(0,2).toUpperCase();
  function normalise(pro){return{id:pro.user_id,businessName:pro.business_name,ownerName:pro.owner_name,category:pro.category_name,rating:Number(pro.average_rating||0),reviews:Number(pro.review_count||0),distance:pro.distance_km===null?null:Number(pro.distance_km).toFixed(1),experience:`${pro.experience_years||0} yrs experience`,startingPrice:Number(pro.starting_price||0),available:pro.availability,initials:initials(pro.business_name),categoryId:pro.category_id,phone:pro.phone}}
  function card(pro){return `<article class="professional-card animate-in"><div class="professional-cover"></div><div class="professional-avatar">${escapeHtml(pro.initials)}</div><div class="professional-body"><div class="professional-heading"><div><h3>${escapeHtml(pro.businessName)}</h3><span class="professional-owner">${escapeHtml(pro.ownerName)} · ${escapeHtml(pro.category)}</span></div><small>${pro.available?'Available':'Busy'}</small></div><div class="rating-row"><span class="star">★</span><span class="rating">${pro.rating.toFixed(1)}</span><span>(${pro.reviews} reviews)</span></div><div class="meta-row"><span>${pro.distance===null?'Nearby':`${pro.distance} km away`}</span><span>${escapeHtml(pro.experience)}</span></div><div class="pricing-row"><div><small>Starting from</small><b>${money(pro.startingPrice)}</b></div><span class="badge">Verified</span></div><div class="card-actions"><a href="${pro.phone?`tel:${encodeURIComponent(pro.phone)}`:'#'}" data-call="${escapeHtml(pro.ownerName)}">Call</a><button data-chat="${pro.id}">Chat</button><button class="book" data-book="${pro.id}">Book now</button></div></div></article>`}
  function render(list,container){
    if(!container)return;
    container.innerHTML=list.length?list.map(card).join(''):'<div class="empty-state"><div class="empty-icon">Search</div><b>No professionals found</b><br>Try a different service or filter.</div>';
    qsa('[data-book]',container).forEach(button=>button.addEventListener('click',()=>openBooking(professionals.find(pro=>pro.id===button.dataset.book))));
    qsa('[data-chat]',container).forEach(button=>button.addEventListener('click',()=>{if(!api.user())location.assign(`../login.html?next=${encodeURIComponent('customer/search.html')}`);else toast('Chat becomes available after a booking request is accepted.')}));
    qsa('[data-call]',container).forEach(link=>link.addEventListener('click',event=>{if(link.getAttribute('href')==='#'){event.preventDefault();toast('Phone number is shared when the professional accepts your request.')}}));
  }
  function filter(query='',options={}){const text=query.trim().toLowerCase();return professionals.filter(pro=>{const match=!text||[pro.businessName,pro.ownerName,pro.category].join(' ').toLowerCase().includes(text);return match&&(!options.rating||pro.rating>=Number(options.rating))&&(!options.distance||pro.distance<=Number(options.distance))&&(!options.available||pro.available)})}
  function openBooking(pro){if(!pro)return;let modal=qs('#bookingModal');if(!modal){modal=document.createElement('div');modal.id='bookingModal';modal.className='modal-backdrop';document.body.append(modal);modal.addEventListener('click',event=>{if(event.target===modal)modal.classList.remove('show')})}modal.innerHTML=`<div class="modal"><div class="modal-head"><div><h3>Book ${escapeHtml(pro.businessName)}</h3><p>Your request is sent instantly and appears in both dashboards.</p></div><button class="close-btn" data-close>×</button></div><div class="notice"><span>✓</span><span><strong>Verified professional</strong>${escapeHtml(pro.ownerName)} starts from ${money(pro.startingPrice)}.</span></div><form data-validate data-api-form="booking" data-provider-id="${pro.id}" data-category-id="${pro.categoryId||''}" data-price="${pro.startingPrice}"><div class="form-grid"><label class="field full">Service needed<input required name="serviceName" value="${escapeHtml(pro.category)} service"><span class="error"></span></label><label class="field">Preferred time<select required name="preferredTime"><option>As soon as possible</option><option>Today, 2-4 PM</option><option>Today, 5-7 PM</option><option>Tomorrow morning</option></select><span class="error"></span></label><label class="field">Estimated visit<input value="${money(pro.startingPrice)}" readonly><span class="error"></span></label><label class="field full">Describe the work<textarea required name="description" placeholder="For example: kitchen tap is leaking"></textarea><span class="error"></span></label></div><div class="form-actions"><span class="badge blue">Secure request</span><button class="primary-btn">Confirm request</button></div></form></div>`;window.Fixindo.validateForm(qs('form',modal));qs('[data-close]',modal).onclick=()=>modal.classList.remove('show');modal.classList.add('show')}
  async function load(){const result=qs('[data-professional-results]');if(!result)return;result.innerHTML='<div class="empty-state"><b>Finding trusted professionals near you...</b></div>';try{const point=window.Fixindo.location?.getSaved?.()||{};const response=await api.providers({latitude:point.latitude,longitude:point.longitude,available:'true'});professionals=response.providers.map(normalise);if(!professionals.length)toast('No verified professionals are available in this local database yet.')}catch(error){professionals=data.professionals;toast('Showing sample results while the service directory reconnects.')}bind()}
  function bind(){const result=qs('[data-professional-results]');if(!result)return;const input=qs('[data-search-input]');const chips=qsa('[data-filter]');let options={};const draw=()=>render(filter(input?.value||'',options),result);if(input)input.addEventListener('input',draw);chips.forEach(chip=>chip.addEventListener('click',()=>{const key=chip.dataset.filter;if(key==='clear'){options={};chips.forEach(item=>item.classList.remove('active'))}else{options[key]=options[key]?null:chip.dataset.value;chip.classList.toggle('active',Boolean(options[key]))}draw()}));draw()}
  document.addEventListener('DOMContentLoaded',load);window.Fixindo.search={filter,render,openBooking};
})();
